### ISSUE TITLE
Inclusion in the Coq Platform

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/math-classes#107]
Dear math-classes Team,

@VincentSE requested here (https://github.com/coq/platform/issues/31) and @palmskog requested here (https://github.com/coq/platform/issues/14) to include your development into the Coq Platform, which is the standard user facing distribution of Coq.

Coq Platform has a "full" and "extended" level. Inclusion in the "full" level requires an explicit statement by the maintainers, that they agree to the [charter](https://github.com/coq/platform/blob/2021.02/charter.md) of the Coq Platform and intend to publish compatible releases for each release of Coq in a reasonable time frame. For the "extended" level the rules are more relaxed. For developments in the "full" level, users should be able to rely on that the package is maintained, so that they can base their own development on it without a large risk that they have to factor it out again later cause of maintenance issues.

Can you please comment in the Coq Platform issues mentioned above if you do want your package included in the Coq Platform in agreement to the Coq Platform [charter](https://github.com/coq/platform/blob/2021.02/charter.md), and if so which level you would prefer?

Best regards,

Michael

**Comment by Zimmi48** [comment]
@spitters I think it's fine to commit to the full level. math-classes releases can be produced on time for each new Coq release given that it is already in Coq's CI.

**Comment by spitters** [comment]
Yes, please put math-classes in the full category.
