### ISSUE TITLE
Please create a tag for Coq 8.18 in Coq Platform 2023.10

### ISSUE THREAD

**Issue by rtetley** [coq-community/math-classes#120]
The Coq team released Coq `8.18.0` on September 7th, 2023.
The corresponding Coq Platform release `2023.10` should be released before **November 30th, 2023**.
It can be delayed in case of difficulties until January 15th, 2023, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (8.17.0) **does not work** with Coq `8.18.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit 7a57556e489989cb38899decf61ea66f4394c60f on repository https://github.com/coq-community/math-classes - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.18, **preferably before October 31st, 2023**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before October 31st, 2023, it will be included in an early Coq Platform beta release of the for Coq 8.18.0.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.18+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.18+beta1.sh) which already supports Coq version `8.18.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/372

**Comment by Zimmi48** [comment]
Hi @rtetley, @MSoegtropIMC, a tag for 8.18 is already available, but there is no opam package for it yet (https://github.com/coq-community/math-classes/releases/tag/8.18.0). I would appreciate it if someone else than me can take care of creating it. I hope we can automate that process in the near future (cf. coq-community/manifesto#49).

**Comment by rtetley** [comment]
Hi @Zimmi48, done ! See https://github.com/coq/opam/pull/2766

**Comment by Zimmi48** [comment]
Thanks! I subscribed to this PR and, as soon as it is merged, I will take care of Corn.

**Comment by rtetley** [comment]
Closing, the platform now contains 8.18.0
