### ISSUE TITLE
Support Coq 8.19

### ISSUE THREAD

**Issue by SnarkBoojum** [coq-community/math-classes#124]
I just tried to compile version 8.18.0 against Coq 8.19, and it didn't work because of various changes ; I think theory/groups.v needs:
```
-    (try bottomup (choice (hints group_cancellation) <- associativity)).
+    (try bottomup (choice (hints group_cancellation) (<- associativity))).
```
because of the new grammar for rewrite_strat, but the error:
```
File "./theory/groups.v", line 42, characters 2-73:
Error: Cannot find a relation to rewrite.
```
still eludes me.

**Comment by proux01** [comment]
Ping @spitters what are your plans here?

**Comment by spitters** [comment]
@SnarkBoojum it would be great if you could send a PR.
Usually, the coqdevs send a PR directly if changes in Coq break the library.

**Comment by proux01** [comment]
@spitters it's not a matter of sending PRs (math-classes is in Coq CI so it's master branch keeps compiling with Coq master), it's a matter of you (the maintainer here) making a release for Coq 8.19.

**Comment by palmskog** [comment]
See https://github.com/coq-community/math-classes/releases/tag/8.19.0 and https://github.com/coq/opam/pull/3023
