### ISSUE TITLE
master branch does not build cleanly (Streams)

### ISSUE THREAD

**Issue by Zdancewic** [coq-community/math-classes#56]
A clean checkout of math-classes fails to build because two files seem to mistakenly import `MathClasses.theory.Streams` instead of `Coq.Lists.Streams`.

The tail end of the build fails with:
```
Warning: in file ./interfaces/canonical_names.v, library MathClasses.theory.Streams is required and has not been found in the loadpath!
COQC interfaces/canonical_names.v
File "./interfaces/canonical_names.v", line 2, characters 0-34:
Warning: Option Automatic Introduction is deprecated
[deprecated-option,deprecated]
File "./interfaces/canonical_names.v", line 3, characters 0-38:
Warning: Option Automatic Coercions Import is deprecated
[deprecated-option,deprecated]
File "./interfaces/canonical_names.v", line 5, characters 15-41:
Error: Unable to locate library MathClasses.theory.Streams.
```

I was able to get past this by changing the imports of `interfaces/canonical_names.v` and `theory/streams.v`.

**Comment by spitters** [comment]
That was introduced by this PR:
https://github.com/math-classes/math-classes/pull/52

This is strange because the CI passed. Perhaps @ppedrot knows more.

**Comment by spitters** [comment]
theory/streams is included in
https://github.com/math-classes/math-classes/blob/master/Make

**Comment by Zdancewic** [comment]
Is  the problem that you have two files with different capitalization? `Streams.v` and `streams.v` both in the theory directory.  At least on OS X, the second overwrites the first.  Perhaps rename the latter?

**Comment by spitters** [comment]
Thanks! Done. I did it directly from the github interface, so hopefully did not create any new problems.

**Comment by Zdancewic** [comment]
It looks like you also need to update the import in `interfaces/canonical_names.v` to be CoqStreams.

**Comment by spitters** [comment]
Thanks. Done.

**Comment by Zimmi48** [comment]
@spitters A piece of advice: when you are not sure that the change will compile, you can do it in another branch and open a PR. This way, Travis will run and will confirm that there are no errors.
