### ISSUE TITLE
master branch undocumented dependency on BigNums

### ISSUE THREAD

**Issue by Zdancewic** [coq-community/math-classes#57]
Even after repairing the Stream dependencies (see: [this issue](https://github.com/math-classes/math-classes/issues/56)), make fails with:

```
COQC implementations/ZType_integers.v
File "./implementations/ZType_integers.v", line 4, characters 2-23:
Error:
Cannot find a physical path bound to logical path matching suffix
Bignums.SpecViaZ.
```

There is an undocumented dependency on the [BigNums](https://github.com/coq/bignums) package.  After building and installing it, math-classes does compile.

**Comment by spitters** [comment]
Thanks for spotting this. The dependency is in the opam file:
https://github.com/math-classes/math-classes/blob/master/opam

I'll add it to the README.

**Comment by Zimmi48** [comment]
The README was updated.
