### ISSUE TITLE
Release a version compatible with Coq 8.10.

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/math-classes#74]
Currently the master branch of math-classes is compatible with Coq 8.6-8.10 + Coq master but the latest release is only compatible with Coq 8.6-8.9. It would be good to tag a new version (and publish it in opam) so that we can start testing corn with Coq 8.10.

Probably best to merge #73 first though.

**Comment by spitters** [comment]
Agreed. Could you do it? I'm currently on holiday.

**Comment by Zimmi48** [comment]
Sure.

**Comment by Zimmi48** [comment]
See the new tag, and coq/opam-coq-archive#832.
