### ISSUE TITLE
Coq-8.11 support

### ISSUE THREAD

**Issue by vzaliva** [coq-community/math-classes#83]
The current OPAM package does not support Coq-8.11. Please consider supporting 8.11
From OPAM package:
```
depends:      "ocaml" "coq" {(>= "8.6" & < "8.11~")} "coq-bignums"
```

**Comment by Zimmi48** [comment]
Done. New release coq-math-classes 8.11.0 supports Coq 8.6-8.11.

**Comment by vzaliva** [comment]
thanks!
