### ISSUE TITLE
Changing to an SPDX-identifiable license

### ISSUE THREAD

**Issue by palmskog** [coq-community/math-classes#87]
I think this is a very important project in coq-community, but with one big drawback, which is its ad-hoc public domain dedication in lieu of a widely recognized license. In some jurisdictions, public domain dedications are not possible, so the international legal status of the project is unclear.

This issue has been [raised before](https://github.com/coq-community/manifesto/issues/38#issuecomment-469614018) by @Zimmi48, who advocated a the SPDX-listed [CC-0](https://creativecommons.org/share-your-work/public-domain/cc0/) or [Unlicense](https://unlicense.org) licenses. I believe the Unlicense is to be preferred since this project has code and not just documentation.

@spitters as the maintainer of the project, how would you view a pull request to change the license to the Unlicense?

**Comment by spitters** [comment]
I agree. Why unlicense instead of MIT?

**Comment by palmskog** [comment]
> I agree. Why unlicense instead of MIT?

I would want to try to stay as close to the intentions of the main author as possible while solving the legal issues (which I think would result in the Unlicense). Note that the license could still be changed to MIT later without legal encumbrance.

Or what do you think @Zimmi48?

**Comment by Zimmi48** [comment]
The Unlicense is still not as widely accepted compared to the MIT license (e.g. I don't think it appears in the official list of "open source" licenses). So I would recommend switching to MIT even if it deviates a bit from the intents of the initial authors.

**Comment by spitters** [comment]
I think MIT is fine with what we had in mind. @robbertkrebbers already said he is fine with it.
