### ISSUE TITLE
Release for Coq 8.12

### ISSUE THREAD

**Issue by palmskog** [coq-community/math-classes#89]
The current release 8.11.0, is not compatible with Coq 8.12. Can we have a new release which supports 8.12?

This would also be the first MIT-licensed release (and could presumably end up in the Coq Platform).

**Comment by spitters** [comment]
Closed by https://github.com/coq-community/math-classes/pull/90

**Comment by palmskog** [comment]
@spitters unfortunately, #90 was just a prerequisite for making a GitHub release (which usually involves creating a tag and submitting a opam package).

With your permission, I can create a GitHub release for 8.12 (which would be named `8.12.0` following previous version names), let me know here if that's OK.

**Comment by spitters** [comment]
That would be excellent.
