### ISSUE TITLE
coq 8.13 support

### ISSUE THREAD

**Issue by vzaliva** [coq-community/math-classes#97]
Please add support for Coq-8.13. The current OPAM version supports up to 8.12.

**Comment by vzaliva** [comment]
I quickly tried to compile /master/ branch with 8.13 and it emits a lot of warnings (mostly about hints) but compiles OK.

**Comment by spitters** [comment]
Should work already. Maybe opam update ?

>  "coq" {(&gt;= "8.11" &amp; &lt; "8.14~") | (= "dev")}
https://github.com/coq-community/math-classes/blob/master/coq-math-classes.opam

**Comment by spitters** [comment]
Thanks @Zimmi48 . You can probably do that with your eyes closed.
Could you do it? I'd need to look up the precise steps.

**Comment by Zimmi48** [comment]
Sure, I will take care of it.

**Comment by vzaliva** [comment]
Anything I can help with? I am stuck as my project dependency now requires 8.13 while I am also using math-classes.

**Comment by Zimmi48** [comment]
Sorry about the delay @vzaliva. I released a new 8.13.0 version (https://github.com/coq-community/math-classes/releases/tag/8.13.0). Are you used to opam packaging? If yes, then you should be able to create the PR updating the opam-coq-archive yourself.

**Comment by vzaliva** [comment]
thanks. yes I can prepare and submit OPAM package update.

**Comment by vzaliva** [comment]
https://github.com/coq/opam-coq-archive/pull/1722
